### ISSUE TITLE
blinkingPeriod

### ISSUE THREAD

**Issue by JTSBerlin** [kayler-renslow/arma-dialog-creator#11]
### Version and Build
1.0.2

### Summary
blinkingPeriod issue

### Detail
blinkingPeriod seems not work correctly or am I wrong? By creating a button for example - it blink and there is no way to disable it. (Viewed this in 'Arma preview (beta)' option. It blink even if you use 0 float number (or 0.00). Clearing the value doesn't help

**Comment by kayler-renslow** [comment]
I think you may be confused on 2 different properties. There is `blinkingPeriod` and a non-configurable period (let's call it `period`). `blinkingPeriod` is controlling the control's entire **opacity**, which will make the entire control/button appear and disappear in the allotted amount of seconds. `period` is for how fast the button's **colors** alternate. If you wish for the *colors* to not alternate, simply set all background colors to be the same (keep in mind that sometimes the text colors alternate as well).

Some controls, e.g. the Shortcut Button (type=16), allow you to configure `period` so that you wouldn't need to set all background colors to be the same. Control type Button (type=1) doesn't appear to have any configurable `period` setting. If Button should have a `period` setting, let me know because from my testing it doesn't exist. :)

Did I answer your question?
