### ISSUE TITLE
Cant open project again if put "&" in structured text

### ISSUE THREAD

**Issue by tuntematonjr** [kayler-renslow/arma-dialog-creator#13]
### Version and Build
Latest 1.0.2

### Summary
Cant open project again if put "&" in structured text

### Detail
So if you put & mark in structured text field. Save and close program. You cant open this project again. Until you remove "&" in project.xml
Here is my test project.
[test.zip](https://github.com/kayler-renslow/arma-dialog-creator/files/1272944/test.zip)

**Comment by kayler-renslow** [comment]
I think that you are not supposed to use standalone & and instead do `&amp;` (as mentioned [here](https://resources.bisimulations.com/wiki/Structured_Text#Ampersand_.28.26.29)).

The reason this is failing is because XML expects more stuff after &.
 Structured text should be able to handle special character codes.

I'll still fix this though because a single character shouldn't break an entire save file.

**Comment by tuntematonjr** [comment]
Ok
I was actually using [&#160](https://community.bistudio.com/wiki/Structured_Text#Notes:)

But good to hear that you are going to fix it. im liking this tool and it is making life so much easier. 
Going to use this more when i have time and report more bugs if i find some.

**Comment by kayler-renslow** [comment]
You'll want to be sure to include the ; as well (&#160;). Both `&amp;` and `&#160;` should be supported because all of the xML parsing is done with a library.

**Comment by tuntematonjr** [comment]
Ok looks like you are right. I did have `;` but some reason i didint copy that.
But tested more with your info and looks like my first problem was wrong and nothing about `&#160;`

The thing what  broke my saves was actually one `ä` in text

**Comment by kayler-renslow** [comment]
That was fixed in https://github.com/kayler-renslow/arma-dialog-creator/commit/1bb311843d4625e9e0c8a6b83bfb687b7a3a5ffd

**Comment by kayler-renslow** [comment]
fix applied in version 1.0.3
